-- To use `ALT+{h,j,k,l}` to navigate windows from any mode:
vim.keymap.set("t", "<M-Left>", "<C-\\><C-N><C-w>h")
vim.keymap.set("t", "<M-Down>", "<C-\\><C-N><C-w>j")
vim.keymap.set("t", "<M-Up>", "<C-\\><C-N><C-w>k")
vim.keymap.set("t", "<M-Right>", "<C-\\><C-N><C-w>l")
vim.keymap.set("i", "<M-Left>", "<C-\\><C-N><C-w>h")
vim.keymap.set("i", "<M-Down>", "<C-\\><C-N><C-w>j")
vim.keymap.set("i", "<M-Up>", "<C-\\><C-N><C-w>k")
vim.keymap.set("i", "<M-Right>", "<C-\\><C-N><C-w>l")
vim.keymap.set("n", "<M-Left>", "<C-w>h")
vim.keymap.set("n", "<M-Down>", "<C-w>j")
vim.keymap.set("n", "<M-Up>", "<C-w>k")
vim.keymap.set("n", "<M-Right>", "<C-w>l")
vim.keymap.set("n", "<M-S-Left>", ":tabprev<CR>")
vim.keymap.set("n", "<M-S-Right>", ":tabnext<CR>")
vim.keymap.set("t", "<M-S-Left>", "<C-\\><C-N>:tabprev<CR>")
vim.keymap.set("t", "<M-S-Right>", "<C-\\><C-N>:tabnext<CR>")
